project:
  type: website
  output-dir: docs
  lib-dir: library
  render:
    - "*.qmd"
    - "!*.Rmd"

website:
  title: "World Politics"
  description: "Course page for POLSC 145 World Politics"
  navbar:
    background: "#512888"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Instructor
      - href: posts.qmd
        text: Blog
      - href: syllabus-s2023.qmd
        text: Syllabus
      - text: "Archives"
        menu:
          - href: syllabi-archive.qmd
            text: Syllabi Archive
          - href: lectures.qmd
            text: Lecture Archive
          - href: https://www.youtube.com/@michaelflynn4243/featured
            text: YouTube Channel
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: article

editor: source

execute:
  freeze: auto
