project:
  type: website
  output-dir: docs
  lib-dir: library
  render:
    - "*.qmd"
    - "!lectures/"
  resources:
    - "files/"
    - "images/"
    - "lectures/*.html"
    - "lectures/*.scss"
    - "lectures/*.css"
    - "lectures/*_files/"
    - "lectures/libs/"
    - "lectures/*.png"
    - "bib/*.csl"
    - "bib/*.bib"

website:
  title: "World Politics"
  description: "Course page for POLSC 145 World Politics"
  navbar:
    background: "#512888"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Instructor
      - href: posts.qmd
        text: Blog
      - text: "Syllabus"
        menu:
          - href: syllabus-s2025.qmd
            text: "Syllabus"
          - href: syllabus-boilerplate-stuff.qmd
            text: "University Syllabus Statements"
      - text: "Archives"
        menu:
          - href: syllabi-archive.qmd
            text: Syllabi Archive
          - href: lectures.qmd
            text: Lecture Archive
          - href: https://www.youtube.com/@michaelflynn4243/featured
            text: YouTube Channel
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: article

editor: source

execute:
  freeze: auto
