---
title: "Lectures"
---

## Lecture Slides

Lectures will be archived here *after* they are given.

0. [Class Introduction](lectures/polsc145-intro-class.html)

1. [Historical Background](lectures/polsc145-historical-background.html)

2. [Social Science Methods](lectures/polsc145-social-science.html)

3. [Explaining War](lectures/polsc145-explaining-war.html)

4. [The Bargaining Model of War](lectures/polsc145-bargaining-model.html)

5. [Domestic Politics and War](lectures/polsc145-domestic-politics-war.html)

6. [International Security Institutions](lectures/polsc145-alliances.html)

7. [The UN and Peacekeeping](lectures/polsc145-collective-security.html)

8. [Civil Wars](lectures/polsc145-civil-wars.html)

9. [Terrorism](lectures/polsc145-terrorism.html)

10. [Trade](lectures/polsc145-trade.html)

11. [Finance](lectures/polsc145-finance.html)

12. [Monetary Policy](lectures/polsc145-monetary-policy.html)

13. [Development](lectures/polsc145-development.html)

14. [Human Rights](lectures/polsc145-human-rights.html)

15. [Environment](lectures/polsc145-environment.html)

16. [Future Challenges](lectures/polsc145-future-challenges.html)
