---
title: 'POLSC 145 Homework #3'
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(peacesciencer)
library(tidyverse)
library(kableExtra)
library(data.table)
knitr::opts_chunk$set(echo = TRUE)

setwd(here::here("homework"))
statedata <- fread("homework-3-data.csv")

countries <- data.table(statename = unique(statedata$statename)) %>% 
  arrange(statename)

sysfonts::font_add_google("Oswald", family = "oswald")
showtext::showtext_auto()

# Windows and Mac seem to process the fotn differently
if (Sys.info()[[1]] == "Windows"){
  
  basesize <- 35
  
} else {
  
  basesize <-  11
  
}

update_geom_defaults("text", list(size = 10, family = "oswald", fontface = "plain", lineheight = 0.2))


# Regular plot theme
theme_flynn <- function(){ 
  
  theme_linedraw(base_size = basesize, base_family = "oswald") %+replace% 
    
    theme(plot.title = element_text(face = "bold", size = basesize * 1.3, hjust = 0, margin = margin(t = 0, b = 0.2, l = 0, r = 0, unit = "cm")),
          plot.subtitle = element_text(size = basesize, hjust = 0, margin = margin(t = 0.0, b = 0.2, unit = "cm")),
          plot.caption = element_text(face = "italic", size = basesize * 0.6, hjust = 1, lineheight = 0.3, margin = margin(t = 0.2, unit = "cm")),
          panel.border = element_rect(fill = NA, size = 0.2),
          strip.background = element_rect(fill = "gray80", color = "black", size = 0.2),
          strip.text = element_text(size = basesize, color = "black", face = "bold", margin = margin(t = 0.2, b = 0.2, l = 0.2, r = 0.2, unit = "cm")),
          panel.background = element_rect(size = 0.2),
          panel.grid.major = element_line(color = "gray70", size = 0.15),
          panel.grid.minor = element_line(color = "gray90", size = 0.1),
          axis.title = element_text(face = "bold", size = basesize),
          axis.title.y = element_text(angle = 90, margin = margin(t = 0, r = 0.2, b = 0, l = 0, unit = "cm")),
          axis.title.x = element_text(margin = margin(t = 0.2, r = 0, b = 0, l = 0, unit = "cm")),
          axis.ticks = element_line(size = 0.1),
          axis.ticks.length = unit(0.1, "cm"),
          legend.title = element_text(size = basesize, face = "bold", hjust = 0, margin = margin(t = 0, b = -0.3, l = 0, r = 0, unit = "cm")),
          legend.text = element_text(size = basesize, hjust = 0, margin = margin(t = 0, b = 0, l = -0.5, r = 0, unit = "cm")),
          legend.box.spacing =  unit(0.2, "cm"),
          plot.margin = margin(0.3, 0.3, 0.3, 0.3, unit = "cm"))
}
```

Inputs {.sidebar}
-----------------------------------------------------------------------


```{r}
selectInput("variable", "Country Name:",
            label = h2("Select your country"),
            choices = countries$statename)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, echo = FALSE}
renderPlot({
    
    tempdata <- statedata %>% 
      mutate(`Country ID` = ifelse(statename == input$variable, "Your Country", "Others")) %>% 
      group_by(year) %>% 
      mutate(medianwars = median(totalwaryears, na.rm = TRUE))
    
    ggplot() +
      geom_line(data = tempdata, aes(x = year, y = totalwaryears, color = `Country ID`, size = `Country ID`, group = statename)) +
      geom_line(data = tempdata, aes(x = year, y = medianwars), size = 2.5, color = "deepskyblue") +
      scale_color_manual(values = c("gray80", "red")) +
      scale_size_manual(values = c(1.0, 2.5)) +
      theme_minimal() +
      labs(x = "Year",
           y = "War-Years",
           title = "Where does your country fall in comparison to others?",
           subtitle = "The blue line is the median war-year count")
  })
```



