---
title: "POLSC 145 Homework #2"
author: "Michael Flynn"
date: "1/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(peacesciencer)
library(tidyverse)
library(kableExtra)
library(data.table)


sysfonts::font_add_google("Oswald", family = "oswald")
showtext::showtext_auto()

# Windows and Mac seem to process the fotn differently
if (Sys.info()[[1]] == "Windows"){
  
  basesize <- 35
  
} else {
  
  basesize <-  11
  
}

update_geom_defaults("text", list(size = 10, family = "oswald", fontface = "plain", lineheight = 0.2))


# Regular plot theme
theme_flynn <- function(){ 
  
  theme_linedraw(base_size = basesize, base_family = "oswald") %+replace% 
    
    theme(plot.title = element_text(face = "bold", size = basesize * 1.3, hjust = 0, margin = margin(t = 0, b = 0.2, l = 0, r = 0, unit = "cm")),
          plot.subtitle = element_text(size = basesize, hjust = 0, margin = margin(t = 0.0, b = 0.2, unit = "cm")),
          plot.caption = element_text(face = "italic", size = basesize * 0.6, hjust = 1, lineheight = 0.3, margin = margin(t = 0.2, unit = "cm")),
          panel.border = element_rect(fill = NA, size = 0.2),
          strip.background = element_rect(fill = "gray80", color = "black", size = 0.2),
          strip.text = element_text(size = basesize, color = "black", face = "bold", margin = margin(t = 0.2, b = 0.2, l = 0.2, r = 0.2, unit = "cm")),
          panel.background = element_rect(size = 0.2),
          panel.grid.major = element_line(color = "gray70", size = 0.15),
          panel.grid.minor = element_line(color = "gray90", size = 0.1),
          axis.title = element_text(face = "bold", size = basesize),
          axis.title.y = element_text(angle = 90, margin = margin(t = 0, r = 0.2, b = 0, l = 0, unit = "cm")),
          axis.title.x = element_text(margin = margin(t = 0.2, r = 0, b = 0, l = 0, unit = "cm")),
          axis.ticks = element_line(size = 0.1),
          axis.ticks.length = unit(0.1, "cm"),
          legend.title = element_text(size = basesize, face = "bold", hjust = 0, margin = margin(t = 0, b = -0.3, l = 0, r = 0, unit = "cm")),
          legend.text = element_text(size = basesize, hjust = 0, margin = margin(t = 0, b = 0, l = -0.5, r = 0, unit = "cm")),
          legend.box.spacing =  unit(0.2, "cm"),
          plot.margin = margin(0.3, 0.3, 0.3, 0.3, unit = "cm"))
}

```

This homework is intended to get you thinking about domestic political conditions, institutions, leaders, and war. 



```{r, echo = FALSE, message=FALSE, warning=FALSE}

wardata <- peacesciencer::cow_war_inter %>% 
  dplyr::select(warnum, ccode1, year) 

system <- peacesciencer::create_stateyears(system = "cow")

wardata <- system %>% 
  left_join(wardata, by = c("ccode" = "ccode1", "year")) %>% 
  group_by(ccode, statenme, year) %>% 
  dplyr::summarise(wars = n_distinct(warnum, na.rm = TRUE))

statedata <- peacesciencer::create_stateyears(system = "cow") %>% 
  add_democracy() %>% 
  add_archigos() %>% 
  dplyr::select(ccode, statenme, year, polity2, leadertransition, n_leaders) %>% 
  group_by(ccode, statenme) %>% 
  mutate(totaltransitions = cumsum(coalesce(leadertransition, 0))) %>% 
  left_join(wardata, by = c("ccode", "year")) %>% 
  dplyr::select(ccode, statenme.x, year, polity2, leadertransition, totaltransitions, wars) %>% 
  group_by(ccode, statenme.x) %>% 
  mutate(totalwaryears = cumsum(wars)) %>% 
  dplyr::rename("statename" = "statenme.x")

fwrite(statedata, here::here("homework/polsc145-homework-3-shiny/homework-3-data.csv"))

table.1 <- statedata %>% 
  kbl(caption = "Data on leaders, regime type, and wars", align = c("rlrrrrrr")) %>% 
  kable_styling(bootstrap_options = "striped") %>% 
  row_spec(0, color = "white", background = "#512888") %>% 
  scroll_box(height = "400px")

table.1

```

```